### ISSUE TITLE
[Bug]: Missing documentation for the flattenConflictedDefinition flag inside swagger-builder

### ISSUE THREAD

**Issue by jendi94** [AmadeusITGroup/otter#1994]
### Package name

showcase-sdk swagger-builder

### Package version

11.0.0

### Reproduction steps

From projects root directory go to packages/@ama-sdk/swagger-builder and open README.md, see _How to use_ section.

### Current result

There is no documentation explaining what the _flattenConflictedDefinition_  flag does and how it works.

### Expected result

There should be such explanation present in the doc.

**Comment by kpanot** [comment]
Hello @jendi94 ,

According to the [Multi Apis](https://github.com/AmadeusITGroup/otter/blob/main/docs/swagger-builder/multi-apis.md) documentation page:

> **flattenConflictedDefinition** merges based interface with new override in case of definition name conflict

This may not be very explicit but concretely, if a definition is created because of name conflict (mainly in case of extension: when a definition will refer another if the same name in a `allOf`) this option will make the builder resolving this `allOf` by itself instead of relying on the code generator composition.

**Comment by jendi94** [comment]
Hi @kpanot ,
I see, thank you. Would it make sense to explicitly describe the flag inside this [readme](https://github.com/AmadeusITGroup/otter/blob/main/docs/swagger-builder/readme.md)?
