### ISSUE TITLE
[Bug]: ng add @o3r/core fails because of globby

### ISSUE THREAD

**Issue by vscaiceanu-1a** [AmadeusITGroup/otter#623]
### Package name

core

### Package version

9.1.0-alpha.48

### Reproduction steps

1. create a new Angular app on 16.1 (or use https://github.com/vscaiceanu-1a/npm-app) 
2. run: `npx @angular/cli@16 add @o3r/core@9.1.0-alpha.48`

### Current result

```shell
ℹ Using package manager: npm
✔ Found compatible package version: @o3r/core@999.0.0.
✔ Package information loaded.

The package @o3r/core@999.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
require() of ES Module /Users/vscaiceanu/workspace/otter/test-apps-o3r/npm-app/node_modules/globby/index.js from /Users/vscaiceanu/workspace/otter/test-apps-o3r/npm-app/node_modules/@o3r/schematics/src/utility/modules.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/vscaiceanu/workspace/otter/test-apps-o3r/npm-app/node_modules/globby/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).


### Expected result

```
✔ Packages installed successfully.
✔ Packages installed successfully.
CREATE src/environments/environment.ts (52 bytes)
CREATE src/environments/environment.development.ts (53 bytes)
CREATE .renovaterc.json (1212 bytes)
UPDATE package.json (1697 bytes)
UPDATE src/app/app.module.ts (1691 bytes)
UPDATE angular.json (3839 bytes)
UPDATE tsconfig.json (775 bytes)
UPDATE .vscode/extensions.json (126 bytes)
✔ Packages installed successfully.

### Additional comments

Workaround: if you run the command again, it works (because `o3r/core` is already installed)

**Comment by kpanot** [comment]
The root causes are the following one:
- ESM is not supported in schematics (cf: https://github.com/angular/angular-cli/issues/22786)
- `ng new` (v16+) generates an application with `globby@13.2.2` which exposes only ESM (no CommonJS exposed from version 12+)
- `@o3r/core` as a peerDep to `"globby": "^11.1.0"` but it is ignore by `ngAdd` process because it is declared as "optional"

The possible solutions (not in preference order):
1. Packaging schematics (rollup, webpack, ...) to bring mandatory dependencies
2. Turn `globby` to "mandatory" dependency (but it would force the user to install it manually before running `ng add @o3r/core`)
3. Define `globby` as "dependency"
4. Discard the case as the application is not part of an Otter Workspace (which would require to add a check in `@o3r/core`'s ngAdd process)

**Comment by fpaul-1A** [comment]
I am no reproducing the issue on my side (Windows / npm)
```
git clone https://github.com/vscaiceanu-1a/npm-app.git
cd npm-app
npm i
npx @angular/cli@16 add @o3r/core@9.1.0-alpha.48
```
all run as expected

also, I don't seem to have such issue on the CI here (also doing ng new + ng add o3r/core) https://github.com/AmadeusITGroup/otter/actions/runs/5801138446/job/15724868827?pr=478#step:11:212 (same for windows/linux . npm/yarn)

could this be something related to your setup ?

**Comment by kpanot** [comment]
I did actually reproduce on Mac (node 20.5.0)

**Comment by pginoux-1A** [comment]
We should first try to upgrade globby (13+?) to not have the default export in the esm module, and check if the issue remains.
